# Generated by Django 5.1.2 on 2024-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence_files/'),
        ),
    ]
