# Generated by Django 5.1.2 on 2024-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_evidence_file_delete_evidencefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='evidence_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
